schema = 3

[mod]
  [mod."github.com/BurntSushi/toml"]
    version = "v1.6.0"
    hash = "sha256-ptdUJvuc21ixeLt+M5way/na3aCnCO4MYHWulWp8NEY="
  [mod."github.com/clipperhouse/displaywidth"]
    version = "v0.8.0"
    hash = "sha256-tAVVr5ZbweMbGDc9gRYz5rPzWPZpsEmVFdAmAssyrrY="
  [mod."github.com/clipperhouse/stringish"]
    version = "v0.1.1"
    hash = "sha256-Mp8M1CRbwr6dcJ4BD9tXD5I78ZgCFEm0GDxJv0GYReg="
  [mod."github.com/clipperhouse/uax29/v2"]
    version = "v2.4.0"
    hash = "sha256-RCLovuNKDvsseU/NrWdDBC7R/ezs81p81YV5GzfP6/Y="
  [mod."github.com/ebitengine/purego"]
    version = "v0.9.1"
    hash = "sha256-iVfU8vaJ7IPa92dUeHeuW+yKvUbe59F/eV7GlDRIAcE="
  [mod."github.com/fatih/color"]
    version = "v1.18.0"
    hash = "sha256-pP5y72FSbi4j/BjyVq/XbAOFjzNjMxZt2R/lFFxGWvY="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.9.0"
    hash = "sha256-WtpE1N6dpHwEvIub7Xp/CrWm0fd6PX7MKA4PV44rp2g="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.14"
    hash = "sha256-JC60PjKj7MvhZmUHTZ9p372FV72I9Mxvli3fivTbxuA="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.19"
    hash = "sha256-GpnbKplhX410Q/eIdknvWbYZgdav1keN+7wNUeOSMHE="
  [mod."github.com/mfridman/interpolate"]
    version = "v0.0.2"
    hash = "sha256-3u04CYOy7PLMctdkum5pltSTkYya8EfXJexbW7j0KB8="
  [mod."github.com/olekukonko/cat"]
    version = "v0.0.0-20250911104152-50322a0618f6"
    hash = "sha256-zkV9QYPu+fXO90ARQ/gn+gDkngJbBFaPqbTU378ki1Y="
  [mod."github.com/olekukonko/errors"]
    version = "v1.2.0"
    hash = "sha256-X/0DVJtYUWuakel8UhqsMDC11W+bX/W4ztPClvTAxHk="
  [mod."github.com/olekukonko/ll"]
    version = "v0.1.4"
    hash = "sha256-kWq1hlnn21E+8k9F1FfXr0v50hlXQSokv8QgGK0Cq88="
  [mod."github.com/olekukonko/tablewriter"]
    version = "v1.1.3"
    hash = "sha256-9doZFXVtyqPDC2H1Zjzx1m2XLDPQRc6EHxacf1uaHmM="
  [mod."github.com/pressly/goose/v3"]
    version = "v3.26.0"
    hash = "sha256-3BoVYxB7n6wPiNuBNzCM8TTFFZE9/aaNM/IP+nLNK4Q="
  [mod."github.com/rogpeppe/go-internal"]
    version = "v1.14.1"
    hash = "sha256-6NzhXCCD1Qhj05WHbCDxH5hwfNM6psoAk7uIxm7N55E="
  [mod."github.com/sethvargo/go-retry"]
    version = "v0.3.0"
    hash = "sha256-1ZnFRHAaQjralGKVRoCbiwCXXB3w4kS3f+2hK9S8lbU="
  [mod."github.com/spf13/cobra"]
    version = "v1.10.2"
    hash = "sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.10"
    hash = "sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU="
  [mod."github.com/tursodatabase/turso-go-platform-libs"]
    version = "v0.4.3"
    hash = "sha256-8dIVrU1Z7GSQ0G+OCdeNZJiAVkc2qgkdHUc3VSe41nI="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."golang.org/x/sync"]
    version = "v0.19.0"
    hash = "sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno="
  [mod."golang.org/x/sys"]
    version = "v0.40.0"
    hash = "sha256-KDe+wMr7dfMFwKMJEljzk+f82pQWFFPoFHivjD7qJGg="
  [mod."golang.org/x/term"]
    version = "v0.39.0"
    hash = "sha256-diP4VknZDlJmhGQdcsXwI2+sFayQdsILFuxK1FBPaUE="
  [mod."golang.org/x/tools"]
    version = "v0.38.0"
    hash = "sha256-GeIkpuKtUfxxrOZLikNlZA3lMKhdyO++PVvXppBGmbw="
  [mod."modernc.org/libc"]
    version = "v1.67.6"
    hash = "sha256-AmcruJSR6Rd6ORFKTm+xSB6G9aqW2dAw/+mWsG2FwcU="
  [mod."turso.tech/database/tursogo"]
    version = "v0.4.3"
    hash = "sha256-u4a8+ceRzZ3TiA1bb30FQCBA+U07ggvG3ApjGRRNtiU="
